language: go
sudo: required
dist: xenial
env:
  - GOTAGS=
  - GOTAGS=trace
go:
  - 1.7
  - 1.8
  - tip
before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure
script:
  - $HOME/gopath/bin/goveralls -service=travis-ci -repotoken $COVERALLS_TOKEN -v
  - go test -race -v -tags "$GOTAGS" $(go list ./... | grep -v '/vendor/')
